authorName: xj
experimentName: test
trialConcurrency: 1
maxExecDuration: 24h
maxTrialNum: 20
#choice: local, remote, pai
trainingServicePlatform: local
searchSpacePath: search_space.json
#choice: true, false
useAnnotation: false
tuner:
  #choice: TPE, Random, Anneal, Evolution, BatchTuner, MetisTuner, GPTuner
  #SMAC (SMAC should be installed through nnictl)
  builtinTunerName: TPE
  classArgs:
    #choice: maximize, minimize
    optimize_mode: maximize
trial:
  command: python main.py
  codeDir: .
  gpuNum: 1

# 当trainingServicePlatform为local时添加如下语句
localConfig:
    useActiveGpu: true
    maxTrialNumPerGpu: 2